### ISSUE TITLE
Compiling with Windows 

### ISSUE THREAD

**Issue by javierpastorfernandez** [huiqu18/WeaklySegMixedAnno#1]
Good evening,
 
Thank you for the work! I am trying to get it working using Anaconda in Windows 10. I also have the following compiler: Microsoft C++ Build Tools: Standalone MSVC compiler, libraries, and scripts. However, it is retrieving an error when trying to build the C++ source files (Related with the version- incompatibility of the compiler I am using): 

![image](https://user-images.githubusercontent.com/60293572/112540441-79144a00-8db2-11eb-9f70-f8eed879d159.png)

Thank you in advance :)

**Comment by huiqu18** [comment]
Hi, we didn't compile or run the code in Windows thus cannot provide useful solutions.

**Comment by javierpastorfernandez** [comment]
Thank you !  I will try to look for a Python machine in my university !
